name: Tester
on: [push]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      
    - name: Install luaJIT
      run: |
       wget http://luajit.org/download/LuaJIT-2.1.0-beta3.zip
       unzip LuaJIT-2.1.0-beta3.zip
       cd LuaJIT-2.1.0-beta3
       make
       ls
       mv src/luajit ../luajit
    
    - name: Get lust
      run: wget https://raw.githubusercontent.com/bjornbytes/lust/master/lust.lua
    
    - name: Run tests with JIT enabled
      run: ./luajit -e "jit.on() dofile('tests.lua')"
    - name: Run tests with JIT disabled
      run: ./luajit -e "jit.off() dofile('tests.lua')"