name: Tester
on: [push]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      
    - name: Install luaJIT
      run: |
       wget http://luajit.org/download/LuaJIT-2.1.0-beta3.zip
       unzip LuaJIT-2.1.0-beta3.zip
       cd LuaJIT-2.1.0
       make && sudo make install