name: Tester
on: [push]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      
    - name: Install lua 5.4
      run: |
       wget https://www.lua.org/ftp/lua-5.4.2.tar.gz
       tar -zxvf lua-5.4.2.tar.gz
       cd lua-5.4.2
       echo MAKING IT NOW
       sudo make install
